# Generated by Django 4.2.3 on 2023-09-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0005_product_image1_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='siginup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
